FROM jruby:9.4.12.0-jdk21@sha256:5641622b488d298362b96fdaea0f328248ce55962e68e224118be11ddb48d16e
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    libicu-dev netbase make ca-certificates && \
    rm -rf /var/lib/apt/lists/*

ENV IS_DOCKER=1

RUN groupadd -g 451 crawlergroup && \
    useradd -m -u 451 -g crawlergroup crawleruser

COPY --chown=451:451 . /home/app
WORKDIR /home/app

# Configure bundler to use HTTP for gem downloads and install gems
RUN export BUNDLER_VERSION="$(cat .bundler-version)" && \
    gem install bundler:${BUNDLER_VERSION} || true && \
    export BUNDLE_SILENCE_ROOT_WARNING=1 && \
    export SCRIPT_BUNDLE=true && \
    bundle config set --local source http://rubygems.org/ && \
    bundle install --no-cache || bundle install || true && \
    chown -R 451:451 /home/app

USER crawleruser

ENTRYPOINT [ "/bin/bash", "-l", "-c" ]
