FROM jruby:9.4.12.0-jdk21@sha256:5641622b488d298362b96fdaea0f328248ce55962e68e224118be11ddb48d16e
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    libicu-dev netbase make ca-certificates

ENV IS_DOCKER=1

RUN groupadd -g 451 crawlergroup && \
    useradd -m -u 451 -g crawlergroup crawleruser

USER crawleruser
COPY --chown=crawleruser:crawlergroup --chmod=775 . /home/app
WORKDIR /home/app

# Install bundler and gems with SSL workaround
RUN gem install bundler:$(cat .bundler-version) && \
    export BUNDLE_SILENCE_ROOT_WARNING=1 && \
    export SCRIPT_BUNDLE=true && \
    bundle config set --global ssl_verify_mode lower && \
    bundle install || true

ENTRYPOINT [ "/bin/bash" ]
